# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Microsoft.WSLg
PackageVersion: 1.0.26
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/microsoft/wslg/releases/download/v1.0.26/wsl_graphics_support_x64.msi
  InstallerSha256: 16877D0A7560B9A98CBEF2CD29B9853249632F473D3DBC7BE418E28613B9EE2E
  ProductCode: '{E04B0005-A349-4BCC-9662-CA0132007E14}'
ManifestType: installer
ManifestVersion: 1.1.0

